title: NSHipster
permalink: /:title/

domains:
  zh-Hans: https://nshipster.cn

author:
  name: 君赏
  email: josercc@nshipster.com
  url: /authors/josercc

markdown: NSHipsterProcessor
highlighter: rouge

kramdown:
  parse_block_html: true
  parse_span_html: true

future: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "translators"
    values:
      layout: "translator"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

groups:
  - Cocoa
  - Swift
  - Xcode
  - Open Source
  - Miscellaneous
  - Trivia
  - Objective-C

include: [".well-known"]

exclude:
  - README*
  - LICENSE*
  - Gemfile*
  - Procfile
  - Rakefile
  - rakelib/
  - netlify.toml
  - _redirects
  - _functions/

assets:
  source_maps: false
  compression: true
  defaults:
    js: { integrity: true }
    css: { integrity: true }
    img: { integrity: true }

jekyll_tidy:
  exclude:
    - robots.txt
    - humans.txt
